### ISSUE TITLE
Firefox only issue

### ISSUE THREAD

**Issue by eurobank** [alastairR/osclass-gdpr#1]
Not a bug of this plugin, since it was the very same with the original gdpr plugin from Osclass org, a few years back. But maybe you can help.

**The checkbox** to agree with GDPR in register page of Osclasswizards 2.0.6. theme doesn't show with Firefox browser. Works fine with Chrome and Edge.

If you can provide some tips or help with this  ....

**Comment by alastairR** [comment]
I've double checked with my customised version of Letgo and the standard Bender with firefox, and it seems ok, I'll find a copy of osclasswizards 2.0.6 and retry with that. With Bender it did not line up the checkbox nicely, and i had to enclose the osc_run_hook('user_register_form') within divs to get it to align with the form text boxes:
```
            <div class="control-group">
                <div class="controls">
            <?php osc_run_hook('user_register_form'); ?>
                </div>
            </div>
```

I'll get back to you

**Comment by alastairR** [comment]
Needs a bit of css to tidy up but:
![osclasswizards](https://user-images.githubusercontent.com/6677574/136715555-a4cbb521-419d-4961-ba9d-718bdd617302.png)
:
Check your user-register.php has the run hook for 'user_register_form', and then use the html inspector in firefox to check the agree check box is there, and check what css is being applied to it.

**Comment by alastairR** [comment]
I should have checked a bit better. I did not try ticking the checkbox!
Curious.
I'll let you know why it is not available, if I can

**Comment by alastairR** [comment]
OK, for some strange reason, the osclasswizard main.css line 54 has input[type="checkbox"] set to visibility: hidden;

I think the easiest way for a non-developer to fix is to add:
`.gdpr-agree input[type="checkbox"] {
visibility: visible;
}`
in the osclasswizards, theme settings, custom css field in the theme style section.

**Comment by eurobank** [comment]
Thanks a million times, works fine now.

**Comment by eurobank** [comment]
Acrually it doesn't work, but that's fine. Not your fault but the theme's.

It shows now but doesn't work. It says You must accept it while you checked it. It doesn't work.
