### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by eurobank** [alastairR/osclass-gdpr#2]
No one can register. Ticked but 

You must accept our "Terms and Conditions" and "Privacy Policy"

is always showing.

Also this seems like a totally untested plugin. Links from Osclass old sites, visual issues in the admin settings here and there.

**Comment by alastairR** [comment]
Thanks for the feed-back.
It seems there was an error I had introduced in the agree checkbox code. That has been fixed.
TBH, I just merged some code I found elsewhere for the popup, and added the email form into the pre-existing GDPR plugin.
Please advise what you consider are visual issues in the admin settings.

**Comment by eurobank** [comment]
I will do that tomorrow and capture the issues.

**Comment by eurobank** [comment]
In this 

https://github.com/alastairR/osclass-gdpr/commit/bdb654e54d9947437885e1a4996b037f9a5879e7

and in other places there is an issue: The GDPR is written GPDR for some reason. I did a search in all files and it is in two php files, alerts.php and in  the classes OsclassGdpr.php.

Not sure if this is an issue, since it is everywhere wrong (and not in some files). 

Pls check it out and if needed fix it.

**Comment by alastairR** [comment]
Thanks for that. I thought the gpdr typo might have been my sloppy typing, but I've double checked, and it was in the original GDPR plugin. It will be fixed.

**Comment by eurobank** [comment]
> 
> 
> Thanks for that. I thought the gpdr typo might have been my sloppy typing, but I've double checked, and it was in the original GDPR plugin. It will be fixed.

The original gdpr plugin was the last plugin they coded, apparently quickly and only one of the Osclass team did it. Carlos something.

**Comment by eurobank** [comment]
Here are some of the small (visual) issues:

![Screenshot (4)](https://user-images.githubusercontent.com/4467158/137697631-14bf41a5-9600-4163-b83c-952863db18ae.png)

![Screenshot (5)](https://user-images.githubusercontent.com/4467158/137697744-4a5b9078-8977-4110-8315-334de1e263e5.png)

The Done buttons seem a little tooo big ...

**Comment by alastairR** [comment]
I've fixed the missing examples and 'done' buttons, but you'd have to uninstall and reinstall to get the examples because they are only set during the install. Those done buttons aren't actually buttons but alert messages. They look a little less like buttons now, but not much.

**Comment by eurobank** [comment]
No worries, i will test and update here.

**Comment by eurobank** [comment]
If you could also fix this:

![Screenshot](https://user-images.githubusercontent.com/4467158/137940922-fa24b703-de2b-4b47-8fd5-4e0c20b72b27.png)

**Comment by alastairR** [comment]
Done
