### ISSUE TITLE
Question about Cookies

### ISSUE THREAD

**Issue by eurobank** [alastairR/osclass-gdpr#3]
@alastairR The Cookies when does it display? I can't make it happen ....

**Comment by alastairR** [comment]
Open the web developer tools in whatever browser you use. Using the 'Inspector', open the Head section and check that gdpr-cookie.js is loaded. Double check the console log to make sure there's no error messages.
The open the 'Storage' section in the tool and delete all the cookies for the site, and refresh the page.
The popup is built, on the fly, by the display function between lines 143 and 294 in gdpr-cookie.js, 
The code that initialises the gdpr popup is inserted by the OsclassGdpr class as a footer hook, so you should be able to see that using the Inspector, as a Script block immediately above the footer block.

Having said all that, I expect it had just created the cookie in a previous test, and that is stopping it from displaying it again.

If you don't want to delve around using the web developer tools, you could add the link mentioned in the readme.md to a web page, and use that to remove the cookie.

**Comment by eurobank** [comment]
ok i will try all that, still WHEN that popup displays? I have NEVER seen it. I mean this
`
By accepting our cookies you grant us permission to store cookies in your browser. You can find more information about what we do with your data: {TERMS}`

**Comment by eurobank** [comment]
No matter what i tried, i see NO cookies set anywhere. I tried with your suggestion (dev tools), i also tried with a addon for the browser. I found no cookie set. And i got no popup whatsoever.

Maybe i miss something?

**Comment by alastairR** [comment]
If the gdpr-cookie.js is loaded and the initialisation script loaded just before the footer, then the popup should be displayed in the bottom right corner of the web page the first time a user accesses the web site. It will continued to be displayed for every page access until they click the 'accept cookie' button on the pop up. After they click the accept button, it creates a cookie, and it is the presence of that cookie that stops the popup from being displayed for future access to the web site.

If you are not getting the popup, and no cookie, then the javascript is not being run for some reason.

Are you able to see the gdpr-cookie.js bening included in the list of scripts at the top of the page source? Are you able to see the gdpr initialisation script just above the footer? Do you get any error messages in the browser console?

**Comment by alastairR** [comment]
I rechecked the plugin by installing on a new system with bender theme, and I've found that when the option for the user to remove their account is not selected, the javascript to initialise the popup is not loaded, and the popup is not displayed. Fixed now.

**Comment by eurobank** [comment]
Now seems to work fine. The colors or the css must be a bit better since with other than bender theme you can't see clearly the options.

Even with bender, it is dark and hard to see.

**Comment by alastairR** [comment]
I'm really lousy at graphic design as you can probably tell, and let the css as it was, copied from elsewhere. You are welcome to suggest an alternate colour scheme. The original css is in .../gdpr/class/OsclassGdpr.php, lines 157 to 227.

**Comment by eurobank** [comment]
Ok, you could make (for that reason) css an external file?
