### ISSUE TITLE
Disable Acceptance for LOGGED in users that use the item contact page

### ISSUE THREAD

**Issue by eurobank** [alastairR/osclass-gdpr#5]
In my opinion when a user registers to use the item contact form (if the option is checked in Osclass settings that only registered users can use the Item Contact), there is no reason to again force him to accept Gdpr.

Any ideas how i can disable that manually (in the code)?

**Comment by alastairR** [comment]
It has to be handled in two places:
- adding the checkbox to the form
- validating the form
I've updated the module to not show the checkbox or validate the response globally for every form if the user is logged in.
So the change applies to the main site contact form as well as the item contact form.
